/**
 * Prisma seed script — populates the Scheme table from frontend mock data.
 * Run with:  npx ts-node src/seed.ts
 *
 * Safe to re-run: uses upsert so existing records are updated, not duplicated.
 *
 * status values:
 *   CURRENT       — scheme is active and running right now
 *   EXPIRED       — deadline passed or scheme discontinued
 *   FUTURE        — announced but application window not yet open
 *   LEGACY_VERIFY — unconfirmed historical record; never shown publicly
 */

import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

interface SchemeSeed {
  id: string;
  name: string;
  shortDescription: string;
  longDescription: string;
  department: string;
  level: string;
  state?: string;
  category: string;
  benefits: { summary: string; amount?: string };
  eligibility: Record<string, unknown>;
  documentsRequired: string[];
  applicationMode: string;
  officialLink?: string;
  deadline?: string;
  /** CURRENT | EXPIRED | FUTURE | LEGACY_VERIFY */
  status: string;
  /** ISO date — when the application window opens (null = no fixed window) */
  applicationStartDate?: string;
  /** ISO date — when the application window closes (null = no fixed window) */
  applicationEndDate?: string;
  tags: string[];
  popularityScore: number;
  launchedYear: number;
  rating?: number;
  sourceUrl?: string;
  lastVerifiedAt?: string;
}

const SCHEMES: SchemeSeed[] = [
  // ── Agriculture ────────────────────────────────────────────────────────────
  {
    id: "pm-kisan",
    name: "PM-KISAN Samman Nidhi",
    shortDescription: "Income support for eligible landholding farmer families.",
    longDescription: "PM-KISAN provides direct income support to eligible farmer families to help with agricultural inputs and household needs.",
    department: "Ministry of Agriculture and Farmers Welfare",
    level: "central", category: "agriculture",
    benefits: { summary: "Direct income support in three installments.", amount: "Rs. 6,000 per year" },
    eligibility: { occupations: ["farmer"], otherCriteria: ["Must be an eligible landholding farmer family"] },
    documentsRequired: ["Aadhaar card", "Land record", "Bank passbook", "Mobile number"],
    applicationMode: "online", officialLink: "https://pmkisan.gov.in/",
    status: "CURRENT",
    // Always open — farmers register anytime
    tags: ["farmer", "income support", "agriculture"],
    popularityScore: 98, launchedYear: 2019, rating: 4.8,
    sourceUrl: "https://pmkisan.gov.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "pm-fasal-bima",
    name: "Pradhan Mantri Fasal Bima Yojana",
    shortDescription: "Crop insurance support against notified natural risks.",
    longDescription: "A crop insurance scheme that helps farmers reduce financial risk from crop loss due to weather events, pests, and other notified risks.",
    department: "Ministry of Agriculture and Farmers Welfare",
    level: "central", category: "agriculture",
    benefits: { summary: "Insurance cover for notified crops at subsidized premium." },
    eligibility: { occupations: ["farmer"], otherCriteria: ["Must cultivate a notified crop in a notified area"] },
    documentsRequired: ["Aadhaar card", "Land record or tenancy document", "Bank passbook", "Sowing certificate"],
    applicationMode: "both", officialLink: "https://pmfby.gov.in/",
    deadline: "2026-09-30",
    status: "CURRENT",
    applicationStartDate: "2026-07-01",
    applicationEndDate: "2026-09-30",
    tags: ["crop insurance", "farmer", "risk"],
    popularityScore: 89, launchedYear: 2016, rating: 4.4,
    sourceUrl: "https://pmfby.gov.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "raitha-siri",
    name: "Karnataka Raitha Siri",
    shortDescription: "Support for millet growers in Karnataka.",
    longDescription: "A state support scheme intended to encourage millet cultivation and improve income resilience among Karnataka farmers.",
    department: "Karnataka Agriculture Department",
    level: "state", state: "Karnataka", category: "agriculture",
    benefits: { summary: "Cultivation support for eligible millet growers.", amount: "Up to Rs. 10,000 per hectare" },
    eligibility: { occupations: ["farmer"], state: "Karnataka", otherCriteria: ["Millet cultivation required"] },
    documentsRequired: ["Aadhaar card", "Land record", "Bank passbook"],
    applicationMode: "offline",
    status: "CURRENT",
    tags: ["millet", "farmer", "Karnataka"],
    popularityScore: 62, launchedYear: 2021, rating: 4.0,
    lastVerifiedAt: "2026-08-01",
  },
  {
    id: "pm-kisan-maan-dhan",
    name: "PM Kisan Maan Dhan Yojana",
    shortDescription: "Pension scheme for small and marginal farmers above 60.",
    longDescription: "PM-KMY is a voluntary and contributory pension scheme for small and marginal farmers. On reaching age 60, they receive Rs. 3,000/month.",
    department: "Ministry of Agriculture and Farmers Welfare",
    level: "central", category: "pension",
    benefits: { summary: "Rs. 3,000 per month pension after age 60.", amount: "Rs. 3,000 per month" },
    eligibility: { minAge: 18, maxAge: 40, occupations: ["farmer"], otherCriteria: ["Small and marginal farmers with up to 2 hectares of land"] },
    documentsRequired: ["Aadhaar card", "Bank passbook", "Land record"],
    applicationMode: "online", officialLink: "https://pmkmy.gov.in/",
    status: "CURRENT",
    tags: ["farmer", "pension", "retirement", "small farmer"],
    popularityScore: 68, launchedYear: 2019, rating: 4.0,
    sourceUrl: "https://pmkmy.gov.in/", lastVerifiedAt: "2026-08-01",
  },

  // ── Health ─────────────────────────────────────────────────────────────────
  {
    id: "ayushman-bharat",
    name: "Ayushman Bharat – PM-JAY",
    shortDescription: "Health cover up to Rs. 5 lakh per year for vulnerable families.",
    longDescription: "Ayushman Bharat Pradhan Mantri Jan Arogya Yojana provides health insurance to over 10 crore poor and vulnerable families, covering hospitalization expenses up to Rs. 5 lakh per year.",
    department: "National Health Authority",
    level: "central", category: "health",
    benefits: { summary: "Cashless hospitalization at empaneled hospitals.", amount: "Up to Rs. 5 lakh per year" },
    eligibility: { otherCriteria: ["Must be listed in SECC 2011 database", "No upper age limit"] },
    documentsRequired: ["Aadhaar card", "Ration card", "SECC 2011 database entry"],
    applicationMode: "online", officialLink: "https://pmjay.gov.in/",
    status: "CURRENT",
    tags: ["health", "insurance", "hospital"],
    popularityScore: 95, launchedYear: 2018, rating: 4.7,
    sourceUrl: "https://pmjay.gov.in/", lastVerifiedAt: "2026-08-01",
  },

  // ── Education ──────────────────────────────────────────────────────────────
  {
    id: "nsp-post-matric",
    name: "National Scholarship Portal – Post Matric",
    shortDescription: "Scholarships for SC/ST/OBC and minority students after Class 10.",
    longDescription: "Post Matric Scholarships are centrally sponsored schemes for students from SC, ST, OBC, EBC, DNT, and minority communities studying at the post-matric level.",
    department: "Ministry of Education",
    level: "central", category: "education",
    benefits: { summary: "Tuition fee, maintenance allowance, and other charges." },
    eligibility: { socialCategories: ["SC", "ST", "OBC", "EBC", "DNT", "Minority"], incomeCeiling: 250000, otherCriteria: ["Must have passed Class 10"] },
    documentsRequired: ["Aadhaar card", "Community certificate", "Income certificate", "Mark sheets", "Bank passbook"],
    applicationMode: "online", officialLink: "https://scholarships.gov.in/",
    deadline: "2026-10-31",
    status: "CURRENT",
    applicationStartDate: "2026-08-01",
    applicationEndDate: "2026-10-31",
    tags: ["scholarship", "education", "SC/ST/OBC"],
    popularityScore: 90, launchedYear: 2016, rating: 4.3,
    sourceUrl: "https://scholarships.gov.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "national-means-merit",
    name: "National Means-cum-Merit Scholarship",
    shortDescription: "Rs. 12,000/year scholarship for meritorious students from Class 9.",
    longDescription: "NMMSS is a centrally sponsored scholarship scheme to award scholarships to meritorious students of economically weaker sections to check their dropout at Class 8 and encourage them to continue their studies.",
    department: "Ministry of Education",
    level: "central", category: "education",
    benefits: { summary: "Rs. 12,000 per year scholarship.", amount: "Rs. 12,000 per year" },
    eligibility: { incomeCeiling: 150000, minAge: 13, maxAge: 18, otherCriteria: ["Must have scored at least 55% in Class 7", "State selection test required"] },
    documentsRequired: ["Aadhaar card", "Income certificate", "Mark sheet (Class 7/8)", "Bank passbook"],
    applicationMode: "online", officialLink: "https://scholarships.gov.in/",
    deadline: "2026-10-31",
    status: "CURRENT",
    applicationStartDate: "2026-09-01",
    applicationEndDate: "2026-10-31",
    tags: ["scholarship", "merit", "EWS", "Class 9"],
    popularityScore: 72, launchedYear: 2008, rating: 4.2,
    sourceUrl: "https://scholarships.gov.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "pm-poshan",
    name: "PM POSHAN (Mid-Day Meal Scheme)",
    shortDescription: "Free hot meals for students in government schools up to Class 8.",
    longDescription: "PM POSHAN provides nutritious hot cooked meals to students in government and government-aided schools from Class 1 to 8, improving nutrition and enrolment.",
    department: "Ministry of Education",
    level: "central", category: "education",
    benefits: { summary: "Free hot mid-day meal on every school day." },
    eligibility: { maxAge: 14, otherCriteria: ["Must be enrolled in government or government-aided school up to Class 8"] },
    documentsRequired: [],
    applicationMode: "offline", officialLink: "https://mdm.nic.in/",
    status: "CURRENT",
    tags: ["nutrition", "school meal", "children"],
    popularityScore: 88, launchedYear: 1995, rating: 4.5,
    sourceUrl: "https://mdm.nic.in/", lastVerifiedAt: "2026-08-01",
  },

  // ── Housing ────────────────────────────────────────────────────────────────
  {
    id: "pmay-urban",
    name: "PMAY – Urban (Housing for All)",
    shortDescription: "Housing subsidy for EWS/LIG/MIG beneficiaries in urban areas.",
    longDescription: "Pradhan Mantri Awas Yojana (Urban) aims to provide affordable housing to the urban poor. It offers interest subsidy on home loans under CLSS and direct beneficiary support under BLC and AHP components.",
    department: "Ministry of Housing and Urban Affairs",
    level: "central", category: "housing",
    benefits: { summary: "Interest subsidy up to Rs. 2.67 lakh on home loan.", amount: "Up to Rs. 2.67 lakh subsidy" },
    eligibility: { incomeCeiling: 1800000, otherCriteria: ["Must not own a pucca house anywhere in India", "First-time home buyer"] },
    documentsRequired: ["Aadhaar card", "Income proof", "Property documents", "Bank passbook"],
    applicationMode: "both", officialLink: "https://pmaymis.gov.in/",
    deadline: "2026-12-31",
    status: "CURRENT",
    applicationStartDate: "2026-01-01",
    applicationEndDate: "2026-12-31",
    tags: ["housing", "urban", "subsidy"],
    popularityScore: 88, launchedYear: 2015, rating: 4.2,
    sourceUrl: "https://pmaymis.gov.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "pmay-gramin",
    name: "PMAY – Gramin (Rural Housing)",
    shortDescription: "Financial assistance for rural BPL households to construct a pucca house.",
    longDescription: "Pradhan Mantri Awas Yojana (Gramin) aims to provide pucca houses to rural houseless households or those living in kutcha/dilapidated houses.",
    department: "Ministry of Rural Development",
    level: "central", category: "housing",
    benefits: { summary: "Financial assistance for house construction.", amount: "Rs. 1.20 lakh (plains) / Rs. 1.30 lakh (hilly areas)" },
    eligibility: { otherCriteria: ["Must be listed in SECC 2011 data", "Must not have a pucca house"] },
    documentsRequired: ["Aadhaar card", "Job card", "Bank passbook", "Land documents"],
    applicationMode: "offline", officialLink: "https://pmayg.nic.in/",
    status: "CURRENT",
    tags: ["housing", "rural", "BPL"],
    popularityScore: 87, launchedYear: 2016, rating: 4.3,
    sourceUrl: "https://pmayg.nic.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "jal-jeevan-mission",
    name: "Jal Jeevan Mission",
    shortDescription: "Tap water connections to every rural household.",
    longDescription: "Jal Jeevan Mission aims to provide safe and adequate drinking water through individual household tap connections to all rural households.",
    department: "Ministry of Jal Shakti",
    level: "central", category: "housing",
    benefits: { summary: "Piped drinking water to every rural home." },
    eligibility: { otherCriteria: ["All rural households in India are eligible"] },
    documentsRequired: [],
    applicationMode: "offline", officialLink: "https://jaljeevanmission.gov.in/",
    status: "CURRENT",
    tags: ["water", "rural", "drinking water", "tap connection"],
    popularityScore: 81, launchedYear: 2019, rating: 4.3,
    sourceUrl: "https://jaljeevanmission.gov.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "swachh-bharat-mission",
    name: "Swachh Bharat Mission – Gramin",
    shortDescription: "Household toilet construction subsidy for rural BPL families.",
    longDescription: "Swachh Bharat Mission (Gramin) aims to eliminate open defecation in rural areas by providing financial assistance for individual household toilet construction.",
    department: "Ministry of Jal Shakti",
    level: "central", category: "housing",
    benefits: { summary: "Financial assistance for toilet construction.", amount: "Rs. 12,000 per toilet" },
    eligibility: { otherCriteria: ["BPL rural household without an existing toilet"] },
    documentsRequired: ["Aadhaar card", "BPL card", "Land documents"],
    applicationMode: "offline", officialLink: "https://sbm.gov.in/",
    status: "CURRENT",
    tags: ["sanitation", "toilet", "rural", "BPL"],
    popularityScore: 79, launchedYear: 2014, rating: 4.2,
    sourceUrl: "https://sbm.gov.in/", lastVerifiedAt: "2026-08-01",
  },

  // ── Employment ─────────────────────────────────────────────────────────────
  {
    id: "mgnregs",
    name: "Mahatma Gandhi NREGS",
    shortDescription: "Guaranteed 100 days of wage employment in rural areas.",
    longDescription: "MGNREGA guarantees 100 days of unskilled manual work per year to every rural household willing to do it, providing a safety net for the rural poor.",
    department: "Ministry of Rural Development",
    level: "central", category: "employment",
    benefits: { summary: "100 days of guaranteed wage employment per year.", amount: "Minimum wages as notified by state" },
    eligibility: { otherCriteria: ["Must be rural resident", "Must be above 18 years of age and willing to do unskilled manual work"] },
    documentsRequired: ["Job card (issued by Gram Panchayat)", "Aadhaar card", "Bank passbook"],
    applicationMode: "offline", officialLink: "https://nrega.nic.in/",
    status: "CURRENT",
    tags: ["employment", "rural", "wages", "MNREGA"],
    popularityScore: 93, launchedYear: 2005, rating: 4.5,
    sourceUrl: "https://nrega.nic.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "skill-india",
    name: "Pradhan Mantri Kaushal Vikas Yojana",
    shortDescription: "Free short-term skill training and certification for youth.",
    longDescription: "PMKVY offers short-term training to youth in industry-relevant skills, followed by assessment and certification. Successful trainees receive monetary rewards.",
    department: "Ministry of Skill Development and Entrepreneurship",
    level: "central", category: "employment",
    benefits: { summary: "Free skill training + certification + monetary reward.", amount: "Monetary reward post-certification" },
    eligibility: { minAge: 15, otherCriteria: ["School/college dropout or seeking better employment"] },
    documentsRequired: ["Aadhaar card", "Educational certificates", "Bank passbook", "Photograph"],
    applicationMode: "online", officialLink: "https://www.pmkvyofficial.org/",
    status: "CURRENT",
    applicationStartDate: "2026-04-01",
    applicationEndDate: "2026-12-31",
    tags: ["skill", "training", "youth", "certification"],
    popularityScore: 83, launchedYear: 2015, rating: 4.1,
    sourceUrl: "https://www.pmkvyofficial.org/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "e-shram",
    name: "e-Shram Portal Registration",
    shortDescription: "National database registration for unorganized workers.",
    longDescription: "e-Shram is a national database of unorganized workers including migrant workers, gig and platform workers, construction workers, domestic workers etc.",
    department: "Ministry of Labour and Employment",
    level: "central", category: "employment",
    benefits: { summary: "ABVKY accidental insurance cover of Rs. 2 lakh + access to future schemes." },
    eligibility: { minAge: 16, maxAge: 59, otherCriteria: ["Must be an unorganized worker", "Not an EPFO or ESIC member"] },
    documentsRequired: ["Aadhaar card", "Bank passbook", "Mobile number linked to Aadhaar"],
    applicationMode: "online", officialLink: "https://eshram.gov.in/",
    status: "CURRENT",
    tags: ["unorganized worker", "registration", "migrant", "gig worker"],
    popularityScore: 77, launchedYear: 2021, rating: 4.0,
    sourceUrl: "https://eshram.gov.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "pradhan-mantri-gram-sadak",
    name: "Pradhan Mantri Gram Sadak Yojana",
    shortDescription: "All-weather road connectivity to unconnected rural habitations.",
    longDescription: "PMGSY provides all-weather road connectivity to eligible unconnected rural habitations, improving mobility and access to markets, schools, and health centers.",
    department: "Ministry of Rural Development",
    level: "central", category: "employment",
    benefits: { summary: "All-weather road construction in rural areas." },
    eligibility: { otherCriteria: ["For unconnected habitations as identified by state governments"] },
    documentsRequired: [],
    applicationMode: "offline", officialLink: "https://pmgsy.nic.in/",
    status: "CURRENT",
    tags: ["road", "rural", "infrastructure", "connectivity"],
    popularityScore: 70, launchedYear: 2000, rating: 4.2,
    sourceUrl: "https://pmgsy.nic.in/", lastVerifiedAt: "2026-08-01",
  },

  // ── Women & Child ──────────────────────────────────────────────────────────
  {
    id: "sukanya-samriddhi",
    name: "Sukanya Samriddhi Yojana",
    shortDescription: "High-interest savings scheme for the girl child.",
    longDescription: "Sukanya Samriddhi Yojana is a small savings instrument by the Government of India to encourage savings for the education and marriage of girl children.",
    department: "Ministry of Finance",
    level: "central", category: "women-child",
    benefits: { summary: "High interest rate savings account for girl child.", amount: "7.6% interest p.a. (tax-exempt)" },
    eligibility: { gender: "female", maxAge: 10, otherCriteria: ["Account to be opened by parent/guardian for girl child below 10 years"] },
    documentsRequired: ["Birth certificate of girl child", "Aadhaar card of parent/guardian", "Address proof"],
    applicationMode: "offline", officialLink: "https://www.nsiindia.gov.in/",
    status: "CURRENT",
    tags: ["girl child", "savings", "education"],
    popularityScore: 85, launchedYear: 2015, rating: 4.6,
    sourceUrl: "https://www.india.gov.in/sukanya-samriddhi-yojana", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "beti-bachao",
    name: "Beti Bachao Beti Padhao",
    shortDescription: "Programme to improve welfare of girls and address declining sex ratio.",
    longDescription: "Beti Bachao Beti Padhao is a tri-ministerial scheme focused on survival, protection, and education of the girl child.",
    department: "Ministry of Women and Child Development",
    level: "central", category: "women-child",
    benefits: { summary: "Awareness campaigns, girl enrolment drives, and community support." },
    eligibility: { gender: "female", otherCriteria: ["Targeted at districts with low sex ratio"] },
    documentsRequired: [],
    applicationMode: "offline", officialLink: "https://wcd.nic.in/",
    status: "CURRENT",
    tags: ["girl child", "education", "awareness"],
    popularityScore: 78, launchedYear: 2015, rating: 4.1,
    lastVerifiedAt: "2026-08-01",
  },
  {
    id: "ujjwala-yojana",
    name: "Pradhan Mantri Ujjwala Yojana",
    shortDescription: "Free LPG connections for BPL households to reduce indoor air pollution.",
    longDescription: "PMUY aims to provide LPG connections to BPL rural households, safeguarding women from indoor air pollution and drudgery of collecting firewood.",
    department: "Ministry of Petroleum and Natural Gas",
    level: "central", category: "women-child",
    benefits: { summary: "Free LPG connection and initial refill.", amount: "Free connection worth Rs. 1,600" },
    eligibility: { gender: "female", otherCriteria: ["Must be a BPL woman over 18", "Must not have a domestic LPG connection"] },
    documentsRequired: ["BPL card", "Aadhaar card", "Bank passbook", "Address proof"],
    applicationMode: "offline", officialLink: "https://pmuy.gov.in/",
    status: "CURRENT",
    tags: ["LPG", "BPL", "women", "cooking gas"],
    popularityScore: 86, launchedYear: 2016, rating: 4.4,
    sourceUrl: "https://pmuy.gov.in/", lastVerifiedAt: "2026-08-01",
  },

  // ── Financial Inclusion ────────────────────────────────────────────────────
  {
    id: "pm-svanidhi",
    name: "PM SVANidhi – Street Vendor Loan",
    shortDescription: "Collateral-free working capital loans for street vendors.",
    longDescription: "PM Street Vendor's AtmaNirbhar Nidhi provides affordable collateral-free working capital loans to street vendors to resume their livelihoods.",
    department: "Ministry of Housing and Urban Affairs",
    level: "central", category: "financial-inclusion",
    benefits: { summary: "Working capital loans up to Rs. 50,000.", amount: "Rs. 10,000 → Rs. 20,000 → Rs. 50,000 (tiered)" },
    eligibility: { occupations: ["street vendor"], otherCriteria: ["Must have a vending certificate or LoR from ULB"] },
    documentsRequired: ["Aadhaar card", "Vendor ID / Certificate of Vending", "Bank passbook"],
    applicationMode: "online", officialLink: "https://pmsvanidhi.mohua.gov.in/",
    status: "CURRENT",
    tags: ["street vendor", "loan", "working capital"],
    popularityScore: 75, launchedYear: 2020, rating: 4.2,
    sourceUrl: "https://pmsvanidhi.mohua.gov.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "pmjjby",
    name: "Pradhan Mantri Jeevan Jyoti Bima Yojana",
    shortDescription: "Life insurance scheme at Rs. 436 per year for ages 18–50.",
    longDescription: "PMJJBY offers renewable one-year life cover of Rs. 2 lakh to subscribers aged 18–50 for an annual premium of Rs. 436.",
    department: "Ministry of Finance",
    level: "central", category: "financial-inclusion",
    benefits: { summary: "Life cover of Rs. 2 lakh on death.", amount: "Rs. 2 lakh on death" },
    eligibility: { minAge: 18, maxAge: 50, otherCriteria: ["Must have a savings bank or post office account"] },
    documentsRequired: ["Aadhaar card", "Bank passbook"],
    applicationMode: "both", officialLink: "https://jansuraksha.gov.in/",
    status: "CURRENT",
    applicationStartDate: "2026-06-01",
    applicationEndDate: "2026-05-31",  // annual renewal window (next year)
    tags: ["life insurance", "low premium", "financial inclusion"],
    popularityScore: 82, launchedYear: 2015, rating: 4.3,
    sourceUrl: "https://jansuraksha.gov.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "pmsby",
    name: "Pradhan Mantri Suraksha Bima Yojana",
    shortDescription: "Accident insurance for Rs. 20 per year covering ages 18–70.",
    longDescription: "PMSBY provides accidental death and disability cover of Rs. 2 lakh for a nominal annual premium of Rs. 20, covering ages 18–70.",
    department: "Ministry of Finance",
    level: "central", category: "financial-inclusion",
    benefits: { summary: "Rs. 2 lakh accidental death/disability cover.", amount: "Rs. 2 lakh" },
    eligibility: { minAge: 18, maxAge: 70, otherCriteria: ["Must have a savings bank or post office account"] },
    documentsRequired: ["Aadhaar card", "Bank passbook"],
    applicationMode: "both", officialLink: "https://jansuraksha.gov.in/",
    status: "CURRENT",
    tags: ["accident insurance", "low premium"],
    popularityScore: 79, launchedYear: 2015, rating: 4.2,
    sourceUrl: "https://jansuraksha.gov.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "digital-india",
    name: "Digital India – Common Services Centres",
    shortDescription: "Government service delivery through 5+ lakh CSC centres.",
    longDescription: "Common Services Centres (CSCs) are digital service delivery points providing government e-services, banking, insurance, education, and health services in rural areas.",
    department: "Ministry of Electronics and Information Technology",
    level: "central", category: "financial-inclusion",
    benefits: { summary: "Access to 300+ government and private services at CSC." },
    eligibility: { otherCriteria: ["Open to all citizens — no eligibility restriction"] },
    documentsRequired: [],
    applicationMode: "both", officialLink: "https://csc.gov.in/",
    status: "CURRENT",
    tags: ["digital", "e-governance", "CSC", "rural"],
    popularityScore: 60, launchedYear: 2006, rating: 4.0,
    sourceUrl: "https://csc.gov.in/", lastVerifiedAt: "2026-08-01",
  },

  // ── Business ───────────────────────────────────────────────────────────────
  {
    id: "mudra-loan",
    name: "Pradhan Mantri MUDRA Yojana",
    shortDescription: "Collateral-free loans up to Rs. 10 lakh for micro enterprises.",
    longDescription: "PMMY provides loans up to Rs. 10 lakh through Shishu, Kishore, and Tarun categories to non-corporate, non-farm micro/small enterprises.",
    department: "Ministry of Finance",
    level: "central", category: "business",
    benefits: { summary: "Collateral-free business loan.", amount: "Up to Rs. 10 lakh" },
    eligibility: { occupations: ["self-employed", "entrepreneur"], otherCriteria: ["Non-corporate, non-farm small/micro enterprise"] },
    documentsRequired: ["Aadhaar card", "Business proof", "Bank statements", "Project report"],
    applicationMode: "both", officialLink: "https://www.mudra.org.in/",
    status: "CURRENT",
    tags: ["loan", "business", "MSME", "entrepreneur"],
    popularityScore: 84, launchedYear: 2015, rating: 4.1,
    sourceUrl: "https://www.mudra.org.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "stand-up-india",
    name: "Stand-Up India",
    shortDescription: "Bank loans between Rs. 10 lakh–1 crore for SC/ST and women entrepreneurs.",
    longDescription: "Stand-Up India facilitates bank loans between Rs. 10 lakh and Rs. 1 crore to SC/ST and/or women borrowers for setting up a greenfield enterprise.",
    department: "Ministry of Finance",
    level: "central", category: "business",
    benefits: { summary: "Bank loan for greenfield enterprises.", amount: "Rs. 10 lakh to Rs. 1 crore" },
    eligibility: { gender: "female", socialCategories: ["SC", "ST"], minAge: 18, otherCriteria: ["At least one SC/ST or woman borrower", "Greenfield enterprise"] },
    documentsRequired: ["Aadhaar card", "Business plan", "Bank account", "Caste/community certificate"],
    applicationMode: "both", officialLink: "https://www.standupmitra.in/",
    status: "CURRENT",
    tags: ["business loan", "women", "SC/ST", "entrepreneur"],
    popularityScore: 71, launchedYear: 2016, rating: 4.0,
    sourceUrl: "https://www.standupmitra.in/", lastVerifiedAt: "2026-08-01",
  },

  // ── Pension ────────────────────────────────────────────────────────────────
  {
    id: "atal-pension",
    name: "Atal Pension Yojana",
    shortDescription: "Guaranteed monthly pension for unorganized sector workers.",
    longDescription: "APY is a government-backed pension scheme for workers in the unorganized sector, offering guaranteed monthly pension between Rs. 1,000–5,000 after age 60.",
    department: "Ministry of Finance",
    level: "central", category: "pension",
    benefits: { summary: "Guaranteed monthly pension after 60.", amount: "Rs. 1,000 – Rs. 5,000 per month" },
    eligibility: { minAge: 18, maxAge: 40, otherCriteria: ["Must have savings bank or post office account", "Must not be an existing EPF/EPS member"] },
    documentsRequired: ["Aadhaar card", "Bank passbook / account details", "Mobile number"],
    applicationMode: "both", officialLink: "https://npscra.nsdl.co.in/",
    status: "CURRENT",
    tags: ["pension", "unorganized sector", "retirement"],
    popularityScore: 80, launchedYear: 2015, rating: 4.2,
    sourceUrl: "https://www.india.gov.in/atal-pension-yojana", lastVerifiedAt: "2026-08-01",
  },

  // ── Senior Citizen ─────────────────────────────────────────────────────────
  {
    id: "senior-citizen-savings",
    name: "Senior Citizen Savings Scheme",
    shortDescription: "High-interest savings scheme for citizens above 60.",
    longDescription: "SCSS offers a guaranteed return savings option for senior citizens with quarterly interest payouts, backed by the Government of India.",
    department: "Ministry of Finance",
    level: "central", category: "senior-citizen",
    benefits: { summary: "Guaranteed quarterly interest payouts.", amount: "8.2% interest p.a." },
    eligibility: { minAge: 60, otherCriteria: ["Retired defence personnel can invest from age 50"] },
    documentsRequired: ["Aadhaar card", "Age proof (birth certificate / passport)", "Bank passbook", "PAN card"],
    applicationMode: "offline", officialLink: "https://www.nsiindia.gov.in/",
    status: "CURRENT",
    tags: ["senior citizen", "savings", "interest"],
    popularityScore: 76, launchedYear: 2004, rating: 4.4,
    lastVerifiedAt: "2026-08-01",
  },

  // ── Disability ─────────────────────────────────────────────────────────────
  {
    id: "igndps",
    name: "Indira Gandhi National Disability Pension Scheme",
    shortDescription: "Monthly pension of Rs. 300 for BPL persons with 80%+ disability.",
    longDescription: "IGNDPS provides monthly social assistance to severely disabled persons who are BPL and aged 18–79 years.",
    department: "Ministry of Rural Development",
    level: "central", category: "disability",
    benefits: { summary: "Monthly pension for disabled BPL persons.", amount: "Rs. 300 per month (Centre) + state top-up" },
    eligibility: { minAge: 18, maxAge: 79, disabilityRequired: true, otherCriteria: ["80% or more disability", "Must be BPL"] },
    documentsRequired: ["Disability certificate (80%+)", "BPL card", "Aadhaar card", "Bank passbook"],
    applicationMode: "offline", officialLink: "https://nsap.nic.in/",
    status: "CURRENT",
    tags: ["disability", "pension", "BPL"],
    popularityScore: 65, launchedYear: 2009, rating: 4.0,
    sourceUrl: "https://nsap.nic.in/", lastVerifiedAt: "2026-08-01",
  },
  {
    id: "assistive-devices",
    name: "Assistance to Disabled Persons (ADIP)",
    shortDescription: "Free/subsidized assistive devices for persons with disabilities.",
    longDescription: "ADIP scheme provides modern, durable, and scientifically manufactured assistive devices to persons with disabilities to restore their physical, social, and psychological capabilities.",
    department: "Ministry of Social Justice and Empowerment",
    level: "central", category: "disability",
    benefits: { summary: "Free or subsidized assistive devices (wheelchairs, calipers, hearing aids, etc.)." },
    eligibility: { disabilityRequired: true, incomeCeiling: 20000, otherCriteria: ["Valid disability certificate", "Monthly income below Rs. 20,000"] },
    documentsRequired: ["Disability certificate", "Income certificate", "Aadhaar card", "Doctor's prescription"],
    applicationMode: "offline", officialLink: "https://disabilityaffairs.gov.in/",
    status: "CURRENT",
    tags: ["disability", "assistive device", "wheelchair", "hearing aid"],
    popularityScore: 58, launchedYear: 1981, rating: 4.1,
    lastVerifiedAt: "2026-08-01",
  },

  // ── Minority ───────────────────────────────────────────────────────────────
  {
    id: "minority-scholarship",
    name: "Pre-Matric Scholarship for Minorities",
    shortDescription: "Scholarships for Class 1–10 students from minority communities.",
    longDescription: "Pre-Matric Scholarships are awarded to students from minority communities studying in Class 1 to 10 to encourage them to continue education.",
    department: "Ministry of Minority Affairs",
    level: "central", category: "minority",
    benefits: { summary: "Scholarship covering admission, tuition, and maintenance." },
    eligibility: { socialCategories: ["Muslim", "Christian", "Sikh", "Buddhist", "Jain", "Parsi"], incomeCeiling: 100000 },
    documentsRequired: ["Aadhaar card", "Community certificate", "Income certificate", "Mark sheets", "Bank passbook"],
    applicationMode: "online", officialLink: "https://scholarships.gov.in/",
    deadline: "2026-10-31",
    status: "CURRENT",
    applicationStartDate: "2026-08-01",
    applicationEndDate: "2026-10-31",
    tags: ["scholarship", "minority", "pre-matric"],
    popularityScore: 67, launchedYear: 2008, rating: 4.0,
    sourceUrl: "https://scholarships.gov.in/", lastVerifiedAt: "2026-08-01",
  },
];

async function main() {
  console.log(`Seeding ${SCHEMES.length} schemes with status + application window data…`);

  for (const s of SCHEMES) {
    await prisma.scheme.upsert({
      where: { id: s.id },
      update: {
        name: s.name,
        shortDescription: s.shortDescription,
        longDescription: s.longDescription,
        department: s.department,
        level: s.level,
        state: s.state ?? null,
        category: s.category,
        benefitsJson: JSON.stringify(s.benefits),
        eligibilityJson: JSON.stringify(s.eligibility),
        documentsJson: JSON.stringify(s.documentsRequired),
        applicationMode: s.applicationMode,
        officialLink: s.officialLink ?? null,
        deadline: s.deadline ?? null,
        status: s.status,
        applicationStartDate: s.applicationStartDate ?? null,
        applicationEndDate: s.applicationEndDate ?? null,
        tagsJson: JSON.stringify(s.tags),
        popularityScore: s.popularityScore,
        launchedYear: s.launchedYear,
        rating: s.rating ?? null,
        sourceUrl: s.sourceUrl ?? null,
        lastVerifiedAt: s.lastVerifiedAt ?? null,
      },
      create: {
        id: s.id,
        name: s.name,
        shortDescription: s.shortDescription,
        longDescription: s.longDescription,
        department: s.department,
        level: s.level,
        state: s.state ?? null,
        category: s.category,
        benefitsJson: JSON.stringify(s.benefits),
        eligibilityJson: JSON.stringify(s.eligibility),
        documentsJson: JSON.stringify(s.documentsRequired),
        applicationMode: s.applicationMode,
        officialLink: s.officialLink ?? null,
        deadline: s.deadline ?? null,
        status: s.status,
        applicationStartDate: s.applicationStartDate ?? null,
        applicationEndDate: s.applicationEndDate ?? null,
        tagsJson: JSON.stringify(s.tags),
        popularityScore: s.popularityScore,
        launchedYear: s.launchedYear,
        rating: s.rating ?? null,
        sourceUrl: s.sourceUrl ?? null,
        lastVerifiedAt: s.lastVerifiedAt ?? null,
      },
    });
    process.stdout.write(".");
  }

  console.log(`\n✓ Seeded ${SCHEMES.length} schemes.`);
}

main()
  .catch((e) => { console.error(e); process.exit(1); })
  .finally(async () => { await prisma.$disconnect(); });
