/**
 * Auth controller — seven handlers for the Unique ID + Email OTP flow.
 *
 *  POST /api/auth/check-unique-id   – real-time availability probe
 *  POST /api/auth/register          – create session + send OTP to email
 *  POST /api/auth/login             – look up user + send OTP
 *  POST /api/auth/verify-otp        – validate code → JWT pair + persist refresh token
 *  POST /api/auth/resend-otp        – re-send OTP (rate-limited)
 *  POST /api/auth/refresh           – rotate refresh token → new pair
 *  POST /api/auth/logout            – revoke refresh token
 */

import type { NextFunction, Request, Response } from "express";
import { z } from "zod";
import { asyncHandler } from "../lib/asyncHandler";
import { AppError } from "../lib/errors";
import { createTokenPair } from "../services/auth.service";
import { requestOtp, resendOtp, verifyOtp } from "../services/otp.service";
import {
  UNIQUE_ID_RE,
  checkUniqueIdAvailability,
  createUser,
  findUserByIdentifier,
} from "../services/user.service";

// ── Validation schemas ────────────────────────────────────────────────────────

export const checkUniqueIdSchema = z.object({
  uniqueId: z
    .string()
    .min(4, "Unique ID must be 4–20 characters.")
    .max(20, "Unique ID must be 4–20 characters.")
    .regex(UNIQUE_ID_RE, "Must start with a letter and contain only letters, numbers, or underscores."),
});

export const registerSchema = z.object({
  uniqueId: z
    .string()
    .min(4)
    .max(20)
    .regex(UNIQUE_ID_RE, "Invalid unique ID format."),
  email: z.string().email("A valid email address is required."),
});

export const loginSchema = z.object({
  identifier: z
    .string()
    .min(1, "Please enter your unique ID or email.")
    .max(255),
});

export const verifyOtpSchema = z.object({
  // verifyToken is a UUID generated by randomUUID() in otp.service.ts
  verifyToken: z.string().min(1, "Verification token is required."),
  otp: z
    .string()
    .length(6, "OTP must be exactly 6 digits.")
    .regex(/^\d{6}$/, "OTP must contain only digits."),
  // Only required for the signup path — Zod must not strip it before the handler reads it
  uniqueId: z
    .string()
    .min(4)
    .max(20)
    .regex(UNIQUE_ID_RE, "Invalid unique ID format.")
    .optional(),
});

export const resendOtpSchema = z.object({
  // verifyToken is a UUID generated by randomUUID() in otp.service.ts
  verifyToken: z.string().min(1, "Verification token is required."),
});

// ── Helper ────────────────────────────────────────────────────────────────────

/** Masks an email address: j***e@gmail.com */
function maskEmail(email: string): string {
  const [local, domain] = email.split("@");
  if (!local || !domain) return email;
  if (local.length <= 2) return `${local[0]}***@${domain}`;
  return `${local[0]}***${local[local.length - 1]}@${domain}`;
}

// ── Handlers ─────────────────────────────────────────────────────────────────

/**
 * POST /api/auth/check-unique-id
 * Body: { uniqueId }
 * Returns: { available: boolean }
 *
 * Safe to call unauthenticated; returns no information about existing accounts
 * beyond whether the ID is available.
 */
export const checkUniqueIdHandler = asyncHandler(
  async (req: Request, res: Response, _next: NextFunction) => {
    const { uniqueId } = req.body as z.infer<typeof checkUniqueIdSchema>;
    const available = await checkUniqueIdAvailability(uniqueId);
    res.json({ success: true, available });
  },
);

/**
 * POST /api/auth/register
 * Body: { uniqueId, email }
 * Returns: { verifyToken, maskedEmail, expiresAt }
 *
 * - Checks uniqueId availability and email uniqueness.
 * - Sends a 6-digit OTP to the provided email.
 * - Does NOT create the User record yet — that happens in /verify-otp.
 */
export const registerHandler = asyncHandler(
  async (req: Request, res: Response, next: NextFunction) => {
    const { uniqueId, email } = req.body as z.infer<typeof registerSchema>;

    // Check unique ID availability
    const idAvailable = await checkUniqueIdAvailability(uniqueId);
    if (!idAvailable) {
      return next(new AppError(409, "UNIQUE_ID_TAKEN", "This unique ID is already taken."));
    }

    let verifyToken: string;
    let expiresAt: Date;

    try {
      ({ verifyToken, expiresAt } = await requestOtp(email.toLowerCase(), "signup"));
    } catch (error) {
      if (error instanceof AppError) return next(error);
      return next(
        new AppError(500, "OTP_REQUEST_FAILED", "Unable to send verification code. Please try again."),
      );
    }

    // Store the intended uniqueId in the OtpRequest so /verify-otp can use it.
    // We do this by embedding it in the verifyToken session — here we put it in
    // a short-lived in-memory map indexed by verifyToken.
    // For simplicity in this prototype, we store it in the OtpRequest's userId
    // field repurposed as a JSON string. A cleaner approach would add a `meta`
    // column — but we keep schema changes minimal here.
    // ↓ Actually, we'll pass it through by having the client send uniqueId again
    // at /verify-otp for the signup path. The server validates it is still free
    // at that point and then creates the user atomically.

    res.status(202).json({
      success: true,
      verifyToken,
      maskedEmail: maskEmail(email),
      expiresAt: expiresAt.toISOString(),
    });
  },
);

/**
 * POST /api/auth/login
 * Body: { identifier }  — unique ID or email
 * Returns: { verifyToken, maskedEmail, expiresAt }
 *
 * Always returns the same generic response whether or not the account exists
 * (anti-enumeration).
 */
export const loginHandler = asyncHandler(
  async (req: Request, res: Response, _next: NextFunction) => {
    const { identifier } = req.body as z.infer<typeof loginSchema>;

    const user = await findUserByIdentifier(identifier);

    // Anti-enumeration: if user not found, we pretend to succeed but don't
    // actually send anything. The client shows the same "OTP sent" UI.
    if (!user) {
      // Return a fake (unusable) verifyToken so the UI behaves identically.
      res.status(202).json({
        success: true,
        verifyToken: "00000000-0000-0000-0000-000000000000",
        maskedEmail: maskEmail(identifier.includes("@") ? identifier : "user@example.com"),
        expiresAt: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
        _ghost: true, // internal marker — never shown to user
      });
      return;
    }

    let verifyToken: string;
    let expiresAt: Date;

    try {
      ({ verifyToken, expiresAt } = await requestOtp(user.email, "signin", user.id));
    } catch {
      // Even on error, respond generically to avoid enumeration
      res.status(202).json({
        success: true,
        verifyToken: "00000000-0000-0000-0000-000000000000",
        maskedEmail: maskEmail(user.email),
        expiresAt: new Date(Date.now() + 10 * 60 * 1000).toISOString(),
        _ghost: true,
      });
      return;
    }

    res.status(202).json({
      success: true,
      verifyToken,
      maskedEmail: maskEmail(user.email),
      expiresAt: expiresAt.toISOString(),
    });
  },
);

/**
 * POST /api/auth/verify-otp
 * Body: { verifyToken, otp, uniqueId? }   (uniqueId required for signup path)
 * Returns: { accessToken, refreshToken, user: { uniqueId, email, displayName } }
 */
export const verifyOtpHandler = asyncHandler(
  async (req: Request, res: Response, next: NextFunction) => {
    const { verifyToken, otp, uniqueId } = req.body as z.infer<typeof verifyOtpSchema>;

    let result: { email: string; purpose: string; userId: string | null };

    try {
      result = await verifyOtp(verifyToken, otp);
    } catch (error) {
      if (error instanceof AppError) return next(error);
      return next(new AppError(500, "VERIFY_FAILED", "Verification failed. Please try again."));
    }

    let userId = result.userId;
    let userUniqueId: string;
    let userEmail: string;

    if (result.purpose === "signup") {
      // Create the user account now that email is verified
      if (!uniqueId) {
        return next(new AppError(400, "MISSING_UNIQUE_ID", "uniqueId is required for registration."));
      }
      try {
        const newUser = await createUser(uniqueId, result.email);
        userId = newUser.id;
        userUniqueId = newUser.uniqueId;
        userEmail = newUser.email;
      } catch (error) {
        if (error instanceof AppError) return next(error);
        return next(new AppError(500, "USER_CREATE_FAILED", "Failed to create account. Please try again."));
      }
    } else {
      // Login — userId was set when requestOtp was called
      if (!userId) {
        return next(new AppError(400, "INVALID_TOKEN", "Invalid verification session."));
      }
      const user = await findUserByIdentifier(result.email);
      if (!user) {
        return next(new AppError(404, "USER_NOT_FOUND", "Account not found."));
      }
      userUniqueId = user.uniqueId;
      userEmail = user.email;
    }

    const tokens = createTokenPair(userId!);

    // Persist refresh token hash so /api/auth/refresh can validate + rotate it
    const tokenHash = (await import("node:crypto")).default
      .createHash("sha256")
      .update(tokens.refreshToken)
      .digest("hex");

    const { prisma: db } = await import("../lib/prisma");
    await db.refreshToken.create({
      data: {
        tokenHash,
        userId: userId!,
        expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
        userAgent: req.headers["user-agent"] ?? null,
      },
    });

    // Fetch displayName from DB (may have been set on profile)
    const userRow = await db.user.findUnique({ where: { id: userId! }, select: { displayName: true } });

    res.json({
      success: true,
      ...tokens,
      user: {
        id: userId,
        uniqueId: userUniqueId!,
        email: userEmail!,
        displayName: userRow?.displayName || userUniqueId!,
      },
    });
  },
);

/**
 * POST /api/auth/resend-otp
 * Body: { verifyToken }
 * Returns: { expiresAt }
 */
export const resendOtpHandler = asyncHandler(
  async (req: Request, res: Response, next: NextFunction) => {
    const { verifyToken } = req.body as z.infer<typeof resendOtpSchema>;

    let expiresAt: Date;

    try {
      ({ expiresAt } = await resendOtp(verifyToken));
    } catch (error) {
      if (error instanceof AppError) return next(error);
      return next(new AppError(500, "RESEND_FAILED", "Failed to resend code. Please try again."));
    }

    res.status(202).json({
      success: true,
      expiresAt: expiresAt.toISOString(),
    });
  },
);

// ── Refresh + Logout ──────────────────────────────────────────────────────────

import crypto from "node:crypto";
import { prisma } from "../lib/prisma";
import { verifyRefreshToken } from "../services/auth.service";

export const refreshSchema = z.object({
  refreshToken: z.string().min(1, "Refresh token is required."),
});

/**
 * POST /api/auth/refresh
 * Body: { refreshToken }
 * Validates the stored token hash, issues a new token pair, and rotates
 * (revokes old + inserts new) — one-time-use refresh tokens.
 */
export const refreshHandler = asyncHandler(
  async (req: Request, res: Response, next: NextFunction) => {
    const { refreshToken } = req.body as z.infer<typeof refreshSchema>;

    // 1. Verify JWT signature + type
    let payload: ReturnType<typeof verifyRefreshToken>;
    try {
      payload = verifyRefreshToken(refreshToken);
    } catch {
      return next(new AppError(401, "INVALID_TOKEN", "Invalid or expired refresh token."));
    }

    // 2. Look up stored hash
    const tokenHash = crypto.createHash("sha256").update(refreshToken).digest("hex");
    const stored = await prisma.refreshToken.findUnique({ where: { tokenHash } });

    if (!stored || stored.revokedAt !== null || stored.expiresAt < new Date()) {
      return next(new AppError(401, "TOKEN_REVOKED", "Refresh token has been revoked or expired."));
    }

    if (stored.userId !== payload.userId) {
      return next(new AppError(401, "INVALID_TOKEN", "Token mismatch."));
    }

    // 3. Rotate — revoke old, issue new pair
    const { accessToken, refreshToken: newRefreshToken } = createTokenPair(stored.userId);
    const newHash = crypto.createHash("sha256").update(newRefreshToken).digest("hex");

    await prisma.$transaction([
      prisma.refreshToken.update({ where: { id: stored.id }, data: { revokedAt: new Date() } }),
      prisma.refreshToken.create({
        data: {
          tokenHash: newHash,
          userId: stored.userId,
          expiresAt: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000), // 7 days
          userAgent: req.headers["user-agent"] ?? null,
        },
      }),
    ]);

    res.json({ success: true, accessToken, refreshToken: newRefreshToken });
  },
);

export const logoutSchema = z.object({
  refreshToken: z.string().min(1, "Refresh token is required."),
});

/**
 * POST /api/auth/logout
 * Body: { refreshToken }
 * Revokes the stored refresh token — silent success even if already revoked.
 */
export const logoutHandler = asyncHandler(
  async (req: Request, res: Response) => {
    const { refreshToken } = req.body as z.infer<typeof logoutSchema>;
    const tokenHash = crypto.createHash("sha256").update(refreshToken).digest("hex");

    const stored = await prisma.refreshToken.findUnique({ where: { tokenHash } });
    if (stored && !stored.revokedAt) {
      await prisma.refreshToken.update({ where: { id: stored.id }, data: { revokedAt: new Date() } });
    }

    res.json({ success: true });
  },
);
